### ISSUE TITLE
ember install fails, but npm install works fine

### ISSUE THREAD

**Issue by bryanhickerson** [tim-evans/ember-autoresize#29]
When I try to install the addon using ember install I get the following error:

```
bryan$ ember install ember-autoresize
version: 1.13.8
Installed packages for tooling via npm.
installing ember-autoresize
undefined is not a function
TypeError: undefined is not a function
    at new RegistryClient (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/node_modules/bower-registry-client/Client.js:8:27)
    at new PackageRepository (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/lib/core/PackageRepository.js:17:28)
    at new Manager (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/lib/core/Manager.js:17:24)
    at new Project (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/lib/core/Project.js:25:21)
    at install (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/lib/commands/install.js:16:15)
    at /Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/lib/commands/index.js:21:32
    at Promise.apply (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:788:41)
    at /Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:1391:14
    at runSingle (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:137:13)
```

I was able to get the addon working using npm and then adding dom-ruler to my bower.json. I'm not sure what kind of environment info you need, but here's my bower.json:

```
{
  "name": "frontend",
  "dependencies": {
    "bootstrap-filestyle": "~1.2.1",
    "bootstrap-sass": "~3.3.5",
    "ember": "2.2.0",
    "ember-cli-shims": "0.0.6",
    "ember-cli-test-loader": "0.2.1",
    "ember-data": "2.2.1",
    "ember-load-initializers": "~0.1.7",
    "ember-qunit": "0.4.13",
    "ember-qunit-notifications": "0.1.0",
    "font-awesome": "~4.4.0",
    "fullcalendar": "~2.4.0",
    "hint.css": "~1.3.5",
    "jquery": "2.1.4",
    "jquery-knob": "~1.2.11",
    "jquery-mockjax": "~2.0.1",
    "loader.js": "3.4.0",
    "moment": ">= 2.8.0",
    "moment-timezone": "0.4.1",
    "qunit": "~1.18.0",
    "ember-uploader": "0.3.9",
    "fullcalendar": "~2.4.0",
    "js-cookie": "2.0.4",
    "dom-ruler": "~0.1.13"
  },
  "devDependencies": {
    "blanket": "~1.1.5"
  }
}
```

**Comment by tim-evans** [comment]
I believe this may have been a broken release. Please try with `0.5.14`.
